version: '3.1'

volumes:
  minecraft_data:

services:
  minecraft:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 25565:25565/tcp
    volumes:
      - type: volume
        source: minecraft_data
        target: /data